### ISSUE TITLE
C1C2: inteiro da saída

### ISSUE THREAD

**Issue by Carlos-Mareco** [Augusto-Fadanelli/EletronicaDigital#2]
## C1C2: inteiro de saída
Seu código verifica o inteiro antes de converter para binário, tal que o inteiro K deve ser -127 < K < 127. Contudo, e se o resultado da soma ou subtração for um inteiro K que não cumpre o espaço de 8 bits, então ele retorna um resultado diferente do esperado.
Logo, não basta apenas verificar os inteiros de entrada, mas também se a soma deles pertence ao intervalo [-127, 127].

**Comment by Augusto-Fadanelli** [comment]
Vou verificar o problema. Obrigado pelo feedback @Carlos-Mareco

**Comment by Augusto-Fadanelli** [comment]
@Carlos-Mareco Não acho que seja necessário tal verificação, pois se considerarmos que a soma máxima seria de 127 + 127 = 254, que seria 2^8-1 (contando com o zero). Ou seja, mesmo com a soma dos valores máximos permitidos, K ainda estaria dentro do espaço de 8 bits.

Segue imagem do resultado do teste:
![image](https://user-images.githubusercontent.com/32231958/120130781-67c63000-c19d-11eb-87d0-ea0343521ffa.png)

**Comment by Carlos-Mareco** [comment]
Estava testando o recurso Issues, valeu por responder

**Comment by Carlos-Mareco** [comment]
@Augusto-Fadanelli seu programa ainda está errado, pois um espaço de 8 bits suporta no máximo 2⁸-1 = 255, mas considerando que o primeiro bit é o do sinal, então temos no máximo 2⁷-1 = 127.
Você mesmo provou isso na imagem do resultado. Veja,
01111111 = 127
01111111 = 127
11111110 = -2

**Comment by Augusto-Fadanelli** [comment]
@Carlos-Mareco verdade, o primeiro bit é referente ao sinal. Não tinha me atentado para esse detalhe.

**Comment by Augusto-Fadanelli** [comment]
Bug corrigido:
![image](https://user-images.githubusercontent.com/32231958/120195996-b7384a80-c1f5-11eb-94b5-c7f3b98b29d0.png)
